.adr-dir, architecture/decisions/0001-record-architecture-decisions.md, architecture/decisions/0002-read-model-in-postgres.md, architecture/decisions/0003-rest-api.md
Add ADR section:
- ADR on REST API adoption
- ADR on PostgreSQL based read model
We introduced the ADR mechanism to keep track of Architectural Changes on the project
N/A (it's not been tested as it's a change on documentation)
=> PE-60 Add ADRs related to REST API decision and Read model in Postgres

Info/index.ts, openapi/index.yaml
Update OpenApi descriptor. Define endpoint to:
- retrieve the list of online merchants
- retrieve the list of offline merchants
- retrieve the details of a merchant together with its published discounts
Definition of API contracts
N/A
=> PE-57 Open API descriptor for CGN operator search API

GetMerchant/__tests__/handler.test.ts, GetMerchant/function.json, GetMerchant/handler.ts, GetMerchant/index.ts, GetMerchant/postgres_queries.ts, env.example, models/AddressModel.ts, models/DiscountModel.ts, models/MerchantProfileModel.ts, models/ProductCategories.ts, package.json, utils/config.ts, yarn.lock
- Add function to retrieve the merchant details by its ID
**Note: Ensure the `discount.staticCode` visibility only to IO app requests will be subject of another PR**
New feature for CGN operator search API
Tested locally in dev environment, and with attached unit tests
=> PE-19 Extract single merchant details

RefreshMaterializedViews/__tests__/handler.test.ts, RefreshMaterializedViews/function.json, RefreshMaterializedViews/handler.ts, RefreshMaterializedViews/index.ts, env.example, utils/config.ts
- Add function to periodically refresh online_merchant materialized view
Needed to keep search result updated on a daily basis.
Tested locally in dev environment, and with attached unit tests
=> PE-20 Refresh materialized views via time-triggered function

GetOnlineMerchants/__tests__/handler.test.ts, GetOnlineMerchants/__tests__/optional_product_category_list_middleware.test.ts, GetOnlineMerchants/__tests__/optional_query_param.test.ts, GetOnlineMerchants/function.json, GetOnlineMerchants/handler.ts, GetOnlineMerchants/index.ts, GetOnlineMerchants/optional_product_category_list_middleware.ts, GetOnlineMerchants/optional_query_param.ts, GetOnlineMerchants/postgres_queries.ts, models/OnlineMerchantModel.ts, models/ProductCategories.ts
Add function to retrieve the list of merchants that offer discounts on an online channel
New feature for CGN operator search API
Tested locally in dev environment, and with attached unit tests
=> PE-20 Online merchants search API

GetMerchant/index.ts, GetOnlineMerchants/index.ts, RefreshMaterializedViews/index.ts, env.example, utils/config.ts, utils/healthcheck.ts, utils/sequelize-options.ts
- Enable Postgres connection over SSL
This capability is required to deploy on Azure
Tested on Azure with manual deployment
=> Add Postgres SSL connection param

GetMerchant/__tests__/handler.test.ts, GetMerchant/handler.ts, GetMerchant/postgres_queries.ts, models/AddressModel.ts, openapi/index.yaml
- Switch to single-line address entries, after Here Autocomplete and Geocoding integration
Mantain compatibility with cgn-onboarding-portal data model
=> Switch to single line address

GetOnlineMerchants/__tests__/handler.test.ts, GetOnlineMerchants/function.json, GetOnlineMerchants/handler.ts, GetOnlineMerchants/index.ts, GetOnlineMerchants/postgres_queries.ts, openapi/index.yaml
- Moved query parameters to body
Tested with Postman
=> Moved query params to body

.vscode/settings.json, .vscode/tasks.json, package.json
=> Fix local settings for manual deploy

GetOfflineMerchants/__tests__/handler.test.ts, GetOfflineMerchants/handler.ts, utils/postgres_queries.ts
- Fixed ordering by searchable_name (case insensitive)
- Fixed rounding of distance
Tested with Postman
=> Fixed ordering and fixed rounding of distance

GetMerchant/__tests__/handler.test.ts, GetMerchant/handler.ts, models/DiscountModel.ts, openapi/index.yaml
Discount model allows to map a discount without a percentage applied.
Discount value is now nullable because of different type of operator's initiatives
unit test
=> [#PE-176] Allow nullable discount value

GetMerchant/__tests__/handler.test.ts, GetMerchant/postgres_queries.ts, GetOfflineMerchants/__tests__/handler.test.ts, GetOnlineMerchants/__tests__/handler.test.ts, GetOnlineMerchants/__tests__/optional_product_category_list_middleware.test.ts, models/ProductCategories.ts, openapi/index.yaml
Change Product categories and related
unit test
=> [#PE-178] Change product categories

.devops/deploy-pipelines.yml, GetMerchant/__tests__/handler.test.ts, GetMerchant/handler.ts, GetMerchant/postgres_queries.ts, GetOnlineMerchants/__tests__/handler.test.ts, GetOnlineMerchants/handler.ts, models/DiscountCodeTypes.ts, models/MerchantProfileModel.ts, models/OnlineMerchantModel.ts, openapi/index.yaml, utils/postgres_queries.ts
* yarn build
* yarn test
* yarn lint
=> [#IC-163] [#IC-164] Updated operator search to return discount code type

.devops/deploy-pipelines.yml
=> little fix to pipeline

.devops/deploy-pipelines.yml
=> fixed endpoint

GetMerchant/index.ts, GetOfflineMerchants/index.ts, GetOnlineMerchants/index.ts, Info/index.ts
=> fixed express paths

GetMerchant/index.ts, GetOfflineMerchants/index.ts, GetOnlineMerchants/index.ts, Info/index.ts
=> fixed slash on express paths

openapi/index.yaml
=> [#IC-209] fixed required

GetMerchant/postgres_queries.ts
=> Fixed group by

GetDiscountBucketCode/postgres_queries.ts
=> Fixed query

GetMerchant/__tests__/handler.test.ts, GetOfflineMerchants/__tests__/handler.test.ts, GetOnlineMerchants/__tests__/handler.test.ts, GetOnlineMerchants/__tests__/optional_product_category_list_middleware.test.ts, models/ProductCategories.ts, openapi/index.yaml
=> changed categories and fixed tests

GetPublishedProductCategories/index.ts
=> fixed endpoint verb

utils/postgres_queries.ts
=> fixed view name

GetOfflineMerchants/__tests__/handler.test.ts, GetOnlineMerchants/__tests__/handler.test.ts, models/ProductCategories.ts
=> Fixed column names for categories

utils/postgres_queries.ts
=> [#PE-306] Fixed queries

models/PublishedProductCategoryModel.ts
=> [#PE-306] Fixed type

GetDiscountBucketCode/index.ts, GetMerchant/index.ts, GetOfflineMerchants/index.ts, GetOnlineMerchants/index.ts, GetPublishedProductCategories/index.ts, RefreshMaterializedViews/index.ts, client/sequelize.ts, utils/sequelize-options.ts
- Centralize Sequelize client creation
- add Connection pool options
This is an hot fix for a production issue on open/close connection via pg
=> Hotfix Sequelize Connection Pool

GetMerchant/__tests__/handler.test.ts, GetMerchant/handler.ts, env.example, jest.config.js
Mapped an empty landing_page_referrer to a "-" when discount has a landing page.
If a landing page url is retrieved without a referrer this fix sends a "-" to IO App, because referrer has become optional but old application version must receive both values to go to the landing page.
yarn build
yarn lint
yarn test
=> [#IOCIT-88] Fixed referrer value to manage its optionality

RefreshMaterializedViews/handler.ts
Added published_product_category view to midnight refresh routine.
A bug was signaled that there were always almost the same categories with new items in the homepage of cgn.
=> [#IOCIT-102] Bugfix refresh category view

RefreshMaterializedViews/__tests__/handler.test.ts
=> fixed test

utils/postgres_queries.ts
Used CURRENT_DATE instead of CURRENT_TIMESTAMP in queries.
CURRENT_DATE checks dates, so it will not check against 00:00:00 time but just the date.
=> [#IOCIT-135] Fixed end date inclusion

.devops/code-review-pipelines.yml, utils/postgres_queries.ts
=> [#IOCIT-276] Removed agreement end date check to get merchant profile

Dangerfile.ts, package.json, yarn.lock
Updated to redis 3.1.2 that is compatible with redis v6
We need to update redis to v6
=> [#IOPID-123] Updated redis client

GetDiscountBucketCode/handler.ts, GetDiscountBucketCode/index.ts, package.json, utils/__tests__/redis_storage.test.ts, utils/redis.ts, utils/redis_storage.ts, yarn.lock
=> Revert "[#IOCIT-289] Updated redis client and usages"
